# Generated by Django 4.2.13 on 2024-05-20 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_personal', '0002_articulo_preview_articulo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sitio_personal/static/img/thumbnails'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='sitio_personal.articulo')),
            ],
        ),
    ]
