# Generated by Django 4.2.13 on 2024-05-20 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio_personal', '0003_alter_articulo_thumbnail_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='likes',
        ),
        migrations.AddField(
            model_name='articulo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
