# Generated by Django 4.2.13 on 2024-05-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_personal', '0005_alter_comentario_options_comentario_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='es_respuesta',
            field=models.BooleanField(default=False),
        ),
    ]
