# Generated by Django 4.2.13 on 2024-06-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_personal', '0009_suscripcion_recibir_notificaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha'], 'permissions': [('highlight_comment', 'Can highlight comment')]},
        ),
    ]
