# Generated by Django 4.2.13 on 2024-06-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio_personal', '0012_comentario_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Iniciar sesión'), ('logout', 'Cerrar sesión'), ('like', 'Like a un post o comentario'), ('dislike', 'Dislike a un post o comentario'), ('comment', 'Realización de un comentario'), ('delete_comment', 'Eliminación de un comentario'), ('create_post', 'Creación de un post'), ('delete_post', 'Eliminación de un post'), ('subscribe', 'Suscripción'), ('unsubscribe', 'Retiro de la suscripción')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
